### ISSUE TITLE
关于域名

### ISSUE THREAD

**Issue by lanbinshijie** [OpenTeens/MercurySQLite_web#6]
- 我需要看下部署预览，我先解析一个我的域名到pages上
 - 如果可以的话解析一个子域名of openteens放到pages上

- 收到的话可以回复这个Issue或者关闭它（推荐回复我以便让所有人都注意到）

@Nathancgy @BernieHuang2008

**Comment by BernieHuang2008** [comment]
网址是啥？mcsql.lanbin.top好像啥都没有

**Comment by BernieHuang2008** [comment]
btw你的域名哪里买的？贵吗？

**Comment by lanbinshijie** [comment]
> btw你的域名哪里买的？贵吗？

啊啊腾讯云注册的，.top 7块一年，.cn 30一年，.net 70一年差不多这个价格

**Comment by lanbinshijie** [comment]
> 网址是啥？mcsql.lanbin.top好像啥都没有

修了一下午，终于搞定自动部署了，现在可以正常写文档了。
@Nathancgy @BernieHuang2008 

之前是因为github action中没有相关build的代码，所以导致部署没有效果，页面很光，重写了action就好了（当然我搞了一晚上）。网址：[mcsql.lanbin.top](https://mcsql.lanbin.top)

**Comment by BernieHuang2008** [comment]
这个图标你设计的吗？

**Comment by lanbinshijie** [comment]
> 这个图标你设计的吗？

DALLE·3 (*/ω＼*)

**Comment by BernieHuang2008** [comment]
666
